name : "Deploy to Server"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v3
      - name: Install Pysftp
        run: |
          pip3 install pysftp
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.x'
          cache: 'npm'
          cache-dependency-path: |
            frontend/package-lock.json
            landing_page/package-lock.json
      - name: Install dependencies
        run: |
          cd frontend
          npm install
          cd ../landing_page
          npm install
      - name: Build
        run: |
          bash build.sh ${{ secrets.SSH_LOCAL_PATH }}
      - name: Deploy
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa
          ssh-keyscan tools.wikilovesfolklore.org
          exit
          python3 deploy.py ${{ secrets.SSH_USER }} id_rsa ${{ secrets.SSH_LOCAL_PATH }} ${{ secrets.SSH_REMOTE_PATH }}
          ssh -i id_rsa "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "sudo /usr/bin/systemctl restart gunicorn"